
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: myapp-db-readonly
  namespace: mynamespace
  annotations:
    creationTimestamp: "2025-09-11T13:02:05Z"
data:
  dbname: myapp_db
  fqdn-jdbc-uri: jdbc:postgresql://postgres-cluster.svc.cluster.local:5432/myapp_db?password=PASSWORD&user=myapp-db-user
  fqdn-uri: postgresql://myapp-db-user:PASSWORD@postgres-cluster.svc.cluster.local:5432/myapp_db
  host: ship-tracking-db-cnpg-rw
  jdbc-uri: jdbc:postgresql://postgres-cluster.svc.cluster.local:5432/myapp_db?password=PASSWORD&user=myapp-db-user
  password: PASSWORD
  pgpass: ship-tracking-db-cnpg-rw:5432:myapp_db:myapp-db-user:PASSWORD
  port: "5432"
  uri: postgresql://myapp-db-user:PASSWORD@postgres-cluster.svc.cluster.local:5432/myapp_db
  user: myapp-db-user
  username: myapp-db-user