apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-secret-operator
  namespace: auto-secret-operator
  labels:
    app: auto-secret-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-secret-operator
  template:
    metadata:
      labels:
        app: auto-secret-operator
    spec:
      serviceAccountName: auto-secret-operator
      containers:
      - name: manager
        image: sindrema/auto-secret-operator:0.1.14
        imagePullPolicy: IfNotPresent
        command:
        - /manager
        args:
        - --leader-elect
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 65532
          readOnlyRootFilesystem: true
