apiVersion: auto-secret.io/v1alpha1
kind: AutoSecretGuid
metadata:
  name: custom-guid-secret
  namespace: mynamespace
  annotations:
    creationTimestamp: "2025-09-11T13:02:05Z"
spec:
  guid: 123e4567-e89b-12d3-a456-426614174000
